import {inject} from 'aurelia-framework';
import {HttpClient} from 'aurelia-fetch-client';
import 'fetch';

@inject(HttpClient)
export class ProductService{

	constructor(http){
		this.products = [
		{
      "id":37520,
      "code":"shirt",
      "name":"Shirt",
      "url":"/p/shirt",
      "slug":"shirt",
      "pricing":{
         "regularPrice":22,
         "salePrice":null,
         "listPrice":null,
         "requireActionForSalePrice":null,
         "recurringPrice":{
            "price":null,
            "startPrice":null,
            "everyXMonths":null,
            "startXMonths":null,
            "thenXMonths":null
         },
         "calculatedPrice":22
      },
      "avgRating":null,
      "imageCollections":[
         {
            "key":"default",
            "images":[
               {
                  "type":"photo",
                  "small":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-2S.jpg",
                  "medium":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-2T.jpg",
                  "large":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-2.jpg"
               },
               {
                  "type":"photo",
                  "small":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-3S.jpg",
                  "medium":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-3T.jpg",
                  "large":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-3.jpg"
               },
               {
                  "type":"photo",
                  "small":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-4S.jpg",
                  "medium":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-4T.jpg",
                  "large":"//cdn3.volusion.com/glvus.qafjh/v/vspfiles/photos/shirt-4.jpg"
               }
            ]
         },
         {
            "key":"purple",
            "images":[
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-3S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-3T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-3.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-4S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-4T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-4.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-5S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-5T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-5.jpg"
               }
            ]
         },
         {
            "key":"orange",
            "images":[
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-T.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-3S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-3T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-3.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-4S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-4T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-4.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-5S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-5T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-5.jpg"
               }
            ]
         },
         {
            "key":"pink",
            "images":[
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-T.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-3S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-3T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-3.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-4S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-4T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-4.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-5S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-5T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-5.jpg"
               }
            ]
         },
         {
            "key":"yellow",
            "images":[
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-T.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-3S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-3T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-3.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-4S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-4T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-4.jpg"
               },
               {
                  "type":"photo",
                  "small":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-5S.jpg",
                  "medium":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-5T.jpg",
                  "large":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-5.jpg"
               }
            ]
         }
      ],
      "options":[
         {
            "key":"color",
            "id":29,
            "label":"Color",
            "class":"color tiles",
            "inputTypes":[
               {
                  "type":"radios"
               }
            ],
            "isRequired":true,
            "derivesToSKU":true,
            "items":[
               {
                  "key":"purple",
                  "id":110,
                  "text":"Purple",
                  "color":null,
                  "swatchImage":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-110-S.jpg"
               },
               {
                  "key":"orange",
                  "id":106,
                  "text":"Orange",
                  "color":null,
                  "swatchImage":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-106-S.jpg"
               },
               {
                  "key":"pink",
                  "id":107,
                  "text":"Pink",
                  "color":null,
                  "swatchImage":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-107-S.jpg"
               },
               {
                  "key":"yellow",
                  "id":112,
                  "text":"Yellow",
                  "color":null,
                  "swatchImage":"http://www.SampleStore.io/v/vspfiles/photos/options/shirt-112-S.jpg"
               }
            ],
            "options":[

            ]
         },
         {
            "key":"size",
            "id":31,
            "label":"Size",
            "class":"size tiles",
            "inputTypes":[
               {
                  "type":"radios"
               }
            ],
            "isRequired":true,
            "derivesToSKU":true,
            "items":[
               {
                  "key":"small",
                  "id":135,
                  "text":"Small",
                  "color":null,
                  "swatchImage":""
               },
               {
                  "key":"medium",
                  "id":137,
                  "text":"Medium",
                  "color":null,
                  "swatchImage":""
               },
               {
                  "key":"large",
                  "id":138,
                  "text":"Large",
                  "color":null,
                  "swatchImage":""
               },
               {
                  "key":"xxxl",
                  "id":136,
                  "text":"XXXL",
                  "color":null,
                  "swatchImage":""
               }
            ],
            "options":[

            ]
         },
         {
            "key":"threadCount",
            "id":43,
            "label":"Thread Count",
            "class":"threadCount tiles",
            "inputTypes":[
               {
                  "type":"radios"
               }
            ],
            "isRequired":true,
            "derivesToSKU":true,
            "items":[
               {
                  "key":"500",
                  "id":183,
                  "text":"500",
                  "color":null,
                  "swatchImage":""
               },
               {
                  "key":"1000",
                  "id":184,
                  "text":"1000",
                  "color":null,
                  "swatchImage":""
               }
            ],
            "options":[

            ]
         }
      ],
      "optionSKUs":[
         {
            "key":"color:purple",
            "quantityInStock":null,
            "sku":null
         },
         {
            "key":"color:purple|size:small|threadCount:500",
            "quantityInStock":10,
            "sku":"shirt-0017"
         },
         {
            "key":"color:purple|size:small|threadCount:1000",
            "quantityInStock":20,
            "sku":"shirt-0033"
         },
         {
            "key":"color:purple|size:medium|threadCount:500",
            "quantityInStock":0,
            "sku":"shirt-0021"
         },
         {
            "key":"color:purple|size:medium|threadCount:1000",
            "quantityInStock":0,
            "sku":"shirt-0037"
         },
         {
            "key":"color:purple|size:large|threadCount:500",
            "quantityInStock":9,
            "sku":"shirt-0025"
         },
         {
            "key":"color:purple|size:large|threadCount:1000",
            "quantityInStock":25,
            "sku":"shirt-0041"
         },
         {
            "key":"color:purple|size:xxxl|threadCount:500",
            "quantityInStock":0,
            "sku":"shirt-0029"
         },
         {
            "key":"color:purple|size:xxxl|threadCount:1000",
            "quantityInStock":0,
            "sku":"shirt-0045"
         },
         {
            "key":"color:orange",
            "quantityInStock":null,
            "sku":null
         },
         {
            "key":"color:orange|size:small|threadCount:500",
            "quantityInStock":21,
            "sku":"shirt-0018"
         },
         {
            "key":"color:orange|size:small|threadCount:1000",
            "quantityInStock":24,
            "sku":"shirt-0034"
         },
         {
            "key":"color:orange|size:medium|threadCount:500",
            "quantityInStock":0,
            "sku":"shirt-0022"
         },
         {
            "key":"color:orange|size:medium|threadCount:1000",
            "quantityInStock":0,
            "sku":"shirt-0038"
         },
         {
            "key":"color:orange|size:large|threadCount:500",
            "quantityInStock":14,
            "sku":"shirt-0026"
         }
      ],
      "cartItem":{
         "qty":1
      },
      "productManufacturer":null,
      "availability":{
         "quantityInStock":null,
         "allowBackOrders":true,
         "description":null
      },
      "seo":{
         "metaTagTitle":"Shirt",
         "metaTagDescription":"Volusion Sample Store - using the new Theme Engine",
         "metaTagKeywords":"Volusion, Theme Engine, Sample Store",
         "globallyAppendedMetatags":null,
         "enableRobotsMetatags":true
      },
      "photoAltText":null,
      "shipping":{
         "weight":1
      },
      "isTaxable":false,
      "isGiftWrapAvailable":false,
      "giftwrap":{
         "price":null
      },
      "descriptions":{
         "detail":"awesome shirt with some colors & sizes sold out, so get it while you can!",
         "short":null,
         "features":null,
         "techSpecs":null,
         "extendedInfo":null,
         "photoCaptionText":null
      },
      "categories":[
         {
            "id":1814,
            "name":"Apparel",
            "slug":"apparel",
            "url":"/c/apparel",
            "breadcrumb":"Apparel"
         },
         {
            "id":1816,
            "name":"Men",
            "slug":"men",
            "url":"/c/men",
            "breadcrumb":"Apparel > Men"
         }
      ]
    }
	];

		/*until api works
		http.configure(config => {
            config
              .useStandardConfiguration()
              .withBaseUrl('http://private-7a928-volusion.apiary-mock.com/api/v1/products');
        });
 
    this.http = http;*/
	}

	getProducts(){

		return this.products;

		/* until the api works
		this.http.fetch("")
			.then(response =adsfasdf
		    console.log(data.description);
		  });*/
	}

	getProduct(id){
		for(let product of this.products){
			if(product.id == id) return product;
		}
	}
}